import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { PhotoDetails } from "@/utils/photos";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <head>
        <title>Portfolio | PyPranav</title>
        {PhotoDetails.certificates.map((url,id)=>(
          <link key={id} rel='preload' href={url?.replace('.jpg','.webp')?.replace('.png','.webp')?.replace('.jpeg','.webp')} as="image"/>
        ))}
        {PhotoDetails.personal.map((url,id)=>(
          <link key={id} rel='preload' href={url?.replace('.jpg','.webp')?.replace('.png','.webp')?.replace('.jpeg','.webp')} as="image"/>
        ))}
        {PhotoDetails.projects.map((url,id)=>(
          <link key={id} rel='preload' href={url?.replace('.jpg','.webp')?.replace('.png','.webp')?.replace('.jpeg','.webp')} as="image"/>
        ))}
      </head>
      <body className={inter.className}>{children}</body>
    </html>
  );
}
